#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Proyecto_Xlorrd")]
	public partial class ProyectoXDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTbl_Usuario(Tbl_Usuario instance);
    partial void UpdateTbl_Usuario(Tbl_Usuario instance);
    partial void DeleteTbl_Usuario(Tbl_Usuario instance);
    partial void InsertTbl_Persona(Tbl_Persona instance);
    partial void UpdateTbl_Persona(Tbl_Persona instance);
    partial void DeleteTbl_Persona(Tbl_Persona instance);
    #endregion
		
		public ProyectoXDataContext() : 
				base(global::Capa_Datos.Properties.Settings.Default.Proyecto_XlorrdConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ProyectoXDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProyectoXDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProyectoXDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProyectoXDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_Usuario> Tbl_Usuario
		{
			get
			{
				return this.GetTable<Tbl_Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Persona> Tbl_Persona
		{
			get
			{
				return this.GetTable<Tbl_Persona>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_actualizar_persona")]
		public int sp_actualizar_persona([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> per_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string per_nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string per_apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> per_cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string per_correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> per_fch_nacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string per_direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> per_fch_creacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Image")] System.Data.Linq.Binary per_imagen, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(2)")] string per_estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), per_id, per_nombre, per_apellido, per_cedula, per_correo, per_fch_nacimiento, per_direccion, per_fch_creacion, per_imagen, per_estado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_verificar_persona")]
		public int sp_verificar_persona([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mensaje", DbType="VarChar(50)")] ref string mensaje, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usu_nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mensaje, usu_nombre);
			mensaje = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_bloquear_persona")]
		public int sp_bloquear_persona([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usu_nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usu_nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_buscar_persona_id")]
		public ISingleResult<sp_buscar_persona_idResult> sp_buscar_persona_id([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> usu_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usu_id);
			return ((ISingleResult<sp_buscar_persona_idResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_buscar_usuario_nombre")]
		public ISingleResult<sp_buscar_usuario_nombreResult> sp_buscar_usuario_nombre([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usu_nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usu_nombre);
			return ((ISingleResult<sp_buscar_usuario_nombreResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_buscar_usuario_persona")]
		public ISingleResult<sp_buscar_usuario_personaResult> sp_buscar_usuario_persona([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> usu_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usu_id);
			return ((ISingleResult<sp_buscar_usuario_personaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_insertar_persona")]
		public int sp_insertar_persona([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string per_nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string per_apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> per_cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string per_correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> per_fch_nacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string per_direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> per_fch_creacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Image")] System.Data.Linq.Binary per_imagen, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(2)")] string per_estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mensaje", DbType="VarChar(50)")] ref string mensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), per_nombre, per_apellido, per_cedula, per_correo, per_fch_nacimiento, per_direccion, per_fch_creacion, per_imagen, per_estado, mensaje);
			mensaje = ((string)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Usuario")]
	public partial class Tbl_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usu_id;
		
		private System.Nullable<int> _per_id;
		
		private string _usu_nombre;
		
		private string _usu_contra;
		
		private string _usu_estado;
		
		private System.Nullable<int> _roll_id;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onper_idChanging(System.Nullable<int> value);
    partial void Onper_idChanged();
    partial void Onusu_nombreChanging(string value);
    partial void Onusu_nombreChanged();
    partial void Onusu_contraChanging(string value);
    partial void Onusu_contraChanged();
    partial void Onusu_estadoChanging(string value);
    partial void Onusu_estadoChanged();
    partial void Onroll_idChanging(System.Nullable<int> value);
    partial void Onroll_idChanged();
    #endregion
		
		public Tbl_Usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_id", DbType="Int")]
		public System.Nullable<int> per_id
		{
			get
			{
				return this._per_id;
			}
			set
			{
				if ((this._per_id != value))
				{
					this.Onper_idChanging(value);
					this.SendPropertyChanging();
					this._per_id = value;
					this.SendPropertyChanged("per_id");
					this.Onper_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nombre", DbType="VarChar(50)")]
		public string usu_nombre
		{
			get
			{
				return this._usu_nombre;
			}
			set
			{
				if ((this._usu_nombre != value))
				{
					this.Onusu_nombreChanging(value);
					this.SendPropertyChanging();
					this._usu_nombre = value;
					this.SendPropertyChanged("usu_nombre");
					this.Onusu_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_contra", DbType="VarChar(50)")]
		public string usu_contra
		{
			get
			{
				return this._usu_contra;
			}
			set
			{
				if ((this._usu_contra != value))
				{
					this.Onusu_contraChanging(value);
					this.SendPropertyChanging();
					this._usu_contra = value;
					this.SendPropertyChanged("usu_contra");
					this.Onusu_contraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_estado", DbType="VarChar(10)")]
		public string usu_estado
		{
			get
			{
				return this._usu_estado;
			}
			set
			{
				if ((this._usu_estado != value))
				{
					this.Onusu_estadoChanging(value);
					this.SendPropertyChanging();
					this._usu_estado = value;
					this.SendPropertyChanged("usu_estado");
					this.Onusu_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roll_id", DbType="Int")]
		public System.Nullable<int> roll_id
		{
			get
			{
				return this._roll_id;
			}
			set
			{
				if ((this._roll_id != value))
				{
					this.Onroll_idChanging(value);
					this.SendPropertyChanging();
					this._roll_id = value;
					this.SendPropertyChanged("roll_id");
					this.Onroll_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Persona")]
	public partial class Tbl_Persona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _per_id;
		
		private string _per_nombre;
		
		private string _per_apellido;
		
		private System.Nullable<int> _per_cedula;
		
		private string _per_correo;
		
		private System.Nullable<System.DateTime> _per_fch_nacimiento;
		
		private string _per_direccion;
		
		private System.Nullable<System.DateTime> _per_fch_creacion;
		
		private System.Data.Linq.Binary _per_imagen;
		
		private string _per_estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onper_idChanging(int value);
    partial void Onper_idChanged();
    partial void Onper_nombreChanging(string value);
    partial void Onper_nombreChanged();
    partial void Onper_apellidoChanging(string value);
    partial void Onper_apellidoChanged();
    partial void Onper_cedulaChanging(System.Nullable<int> value);
    partial void Onper_cedulaChanged();
    partial void Onper_correoChanging(string value);
    partial void Onper_correoChanged();
    partial void Onper_fch_nacimientoChanging(System.Nullable<System.DateTime> value);
    partial void Onper_fch_nacimientoChanged();
    partial void Onper_direccionChanging(string value);
    partial void Onper_direccionChanged();
    partial void Onper_fch_creacionChanging(System.Nullable<System.DateTime> value);
    partial void Onper_fch_creacionChanged();
    partial void Onper_imagenChanging(System.Data.Linq.Binary value);
    partial void Onper_imagenChanged();
    partial void Onper_estadoChanging(string value);
    partial void Onper_estadoChanged();
    #endregion
		
		public Tbl_Persona()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int per_id
		{
			get
			{
				return this._per_id;
			}
			set
			{
				if ((this._per_id != value))
				{
					this.Onper_idChanging(value);
					this.SendPropertyChanging();
					this._per_id = value;
					this.SendPropertyChanged("per_id");
					this.Onper_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_nombre", DbType="VarChar(50)")]
		public string per_nombre
		{
			get
			{
				return this._per_nombre;
			}
			set
			{
				if ((this._per_nombre != value))
				{
					this.Onper_nombreChanging(value);
					this.SendPropertyChanging();
					this._per_nombre = value;
					this.SendPropertyChanged("per_nombre");
					this.Onper_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_apellido", DbType="VarChar(50)")]
		public string per_apellido
		{
			get
			{
				return this._per_apellido;
			}
			set
			{
				if ((this._per_apellido != value))
				{
					this.Onper_apellidoChanging(value);
					this.SendPropertyChanging();
					this._per_apellido = value;
					this.SendPropertyChanged("per_apellido");
					this.Onper_apellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_cedula", DbType="Int")]
		public System.Nullable<int> per_cedula
		{
			get
			{
				return this._per_cedula;
			}
			set
			{
				if ((this._per_cedula != value))
				{
					this.Onper_cedulaChanging(value);
					this.SendPropertyChanging();
					this._per_cedula = value;
					this.SendPropertyChanged("per_cedula");
					this.Onper_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_correo", DbType="VarChar(50)")]
		public string per_correo
		{
			get
			{
				return this._per_correo;
			}
			set
			{
				if ((this._per_correo != value))
				{
					this.Onper_correoChanging(value);
					this.SendPropertyChanging();
					this._per_correo = value;
					this.SendPropertyChanged("per_correo");
					this.Onper_correoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_fch_nacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> per_fch_nacimiento
		{
			get
			{
				return this._per_fch_nacimiento;
			}
			set
			{
				if ((this._per_fch_nacimiento != value))
				{
					this.Onper_fch_nacimientoChanging(value);
					this.SendPropertyChanging();
					this._per_fch_nacimiento = value;
					this.SendPropertyChanged("per_fch_nacimiento");
					this.Onper_fch_nacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_direccion", DbType="VarChar(50)")]
		public string per_direccion
		{
			get
			{
				return this._per_direccion;
			}
			set
			{
				if ((this._per_direccion != value))
				{
					this.Onper_direccionChanging(value);
					this.SendPropertyChanging();
					this._per_direccion = value;
					this.SendPropertyChanged("per_direccion");
					this.Onper_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_fch_creacion", DbType="Date")]
		public System.Nullable<System.DateTime> per_fch_creacion
		{
			get
			{
				return this._per_fch_creacion;
			}
			set
			{
				if ((this._per_fch_creacion != value))
				{
					this.Onper_fch_creacionChanging(value);
					this.SendPropertyChanging();
					this._per_fch_creacion = value;
					this.SendPropertyChanged("per_fch_creacion");
					this.Onper_fch_creacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_imagen", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary per_imagen
		{
			get
			{
				return this._per_imagen;
			}
			set
			{
				if ((this._per_imagen != value))
				{
					this.Onper_imagenChanging(value);
					this.SendPropertyChanging();
					this._per_imagen = value;
					this.SendPropertyChanged("per_imagen");
					this.Onper_imagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_estado", DbType="Char(2)")]
		public string per_estado
		{
			get
			{
				return this._per_estado;
			}
			set
			{
				if ((this._per_estado != value))
				{
					this.Onper_estadoChanging(value);
					this.SendPropertyChanging();
					this._per_estado = value;
					this.SendPropertyChanged("per_estado");
					this.Onper_estadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_buscar_persona_idResult
	{
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.Nullable<int> _Cédula;
		
		private string _Mail;
		
		private string _Fch_Nacimiento;
		
		private string _Dirección;
		
		private string _Fch_Creación;
		
		private System.Data.Linq.Binary _per_imagen;
		
		public sp_buscar_persona_idResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cédula", DbType="Int")]
		public System.Nullable<int> Cédula
		{
			get
			{
				return this._Cédula;
			}
			set
			{
				if ((this._Cédula != value))
				{
					this._Cédula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="VarChar(50)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this._Mail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fch_Nacimiento", DbType="VarChar(10)")]
		public string Fch_Nacimiento
		{
			get
			{
				return this._Fch_Nacimiento;
			}
			set
			{
				if ((this._Fch_Nacimiento != value))
				{
					this._Fch_Nacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dirección", DbType="VarChar(50)")]
		public string Dirección
		{
			get
			{
				return this._Dirección;
			}
			set
			{
				if ((this._Dirección != value))
				{
					this._Dirección = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fch_Creación", DbType="VarChar(10)")]
		public string Fch_Creación
		{
			get
			{
				return this._Fch_Creación;
			}
			set
			{
				if ((this._Fch_Creación != value))
				{
					this._Fch_Creación = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_imagen", DbType="Image")]
		public System.Data.Linq.Binary per_imagen
		{
			get
			{
				return this._per_imagen;
			}
			set
			{
				if ((this._per_imagen != value))
				{
					this._per_imagen = value;
				}
			}
		}
	}
	
	public partial class sp_buscar_usuario_nombreResult
	{
		
		private int _ID;
		
		private string _Alias;
		
		public sp_buscar_usuario_nombreResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alias", DbType="VarChar(50)")]
		public string Alias
		{
			get
			{
				return this._Alias;
			}
			set
			{
				if ((this._Alias != value))
				{
					this._Alias = value;
				}
			}
		}
	}
	
	public partial class sp_buscar_usuario_personaResult
	{
		
		private int _per_id;
		
		private int _usu_id;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.Nullable<int> _Cédula;
		
		private string _Mail;
		
		private string _Fch_Nacimiento;
		
		private string _Dirección;
		
		private string _Fch_Creación;
		
		private string _Alias;
		
		private System.Data.Linq.Binary _Imagen;
		
		public sp_buscar_usuario_personaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_id", DbType="Int NOT NULL")]
		public int per_id
		{
			get
			{
				return this._per_id;
			}
			set
			{
				if ((this._per_id != value))
				{
					this._per_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", DbType="Int NOT NULL")]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					this._usu_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cédula", DbType="Int")]
		public System.Nullable<int> Cédula
		{
			get
			{
				return this._Cédula;
			}
			set
			{
				if ((this._Cédula != value))
				{
					this._Cédula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="VarChar(50)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this._Mail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fch_Nacimiento", DbType="VarChar(10)")]
		public string Fch_Nacimiento
		{
			get
			{
				return this._Fch_Nacimiento;
			}
			set
			{
				if ((this._Fch_Nacimiento != value))
				{
					this._Fch_Nacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dirección", DbType="VarChar(50)")]
		public string Dirección
		{
			get
			{
				return this._Dirección;
			}
			set
			{
				if ((this._Dirección != value))
				{
					this._Dirección = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fch_Creación", DbType="VarChar(10)")]
		public string Fch_Creación
		{
			get
			{
				return this._Fch_Creación;
			}
			set
			{
				if ((this._Fch_Creación != value))
				{
					this._Fch_Creación = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alias", DbType="VarChar(50)")]
		public string Alias
		{
			get
			{
				return this._Alias;
			}
			set
			{
				if ((this._Alias != value))
				{
					this._Alias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen", DbType="Image")]
		public System.Data.Linq.Binary Imagen
		{
			get
			{
				return this._Imagen;
			}
			set
			{
				if ((this._Imagen != value))
				{
					this._Imagen = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
