<?xml version="1.0" encoding="utf-8"?><Database Name="Proyecto_Xlorrd" Class="ProyectoXDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Proyecto_Xlorrd;Integrated Security=True" SettingsObjectName="Capa_Datos.Properties.Settings" SettingsPropertyName="Proyecto_XlorrdConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tbl_Usuario" Member="Tbl_Usuario">
    <Type Name="Tbl_Usuario">
      <Column Name="usu_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="per_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="usu_nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usu_contra" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usu_estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="roll_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Persona" Member="Tbl_Persona">
    <Type Name="Tbl_Persona">
      <Column Name="per_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="per_nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="per_apellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="per_cedula" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="per_correo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="per_fch_nacimiento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="per_direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="per_fch_creacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="per_imagen" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="per_estado" Type="System.String" DbType="Char(2)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_actualizar_persona" Method="sp_actualizar_persona">
    <Parameter Name="per_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="per_nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="per_apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="per_cedula" Type="System.Int32" DbType="Int" />
    <Parameter Name="per_correo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="per_fch_nacimiento" Type="System.DateTime" DbType="Date" />
    <Parameter Name="per_direccion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="per_fch_creacion" Type="System.DateTime" DbType="Date" />
    <Parameter Name="per_imagen" Type="System.Data.Linq.Binary" DbType="Image" />
    <Parameter Name="per_estado" Type="System.String" DbType="Char(2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_verificar_persona" Method="sp_verificar_persona">
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="VarChar(50)" Direction="InOut" />
    <Parameter Name="usu_nombre" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_bloquear_persona" Method="sp_bloquear_persona">
    <Parameter Name="usu_nombre" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_buscar_persona_id" Method="sp_buscar_persona_id">
    <Parameter Name="usu_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_buscar_persona_idResult">
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cédula" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fch_Nacimiento" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Dirección" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fch_Creación" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="per_imagen" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_buscar_usuario_nombre" Method="sp_buscar_usuario_nombre">
    <Parameter Name="usu_nombre" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_buscar_usuario_nombreResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Alias" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_buscar_usuario_persona" Method="sp_buscar_usuario_persona">
    <Parameter Name="usu_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_buscar_usuario_personaResult">
      <Column Name="per_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="usu_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cédula" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fch_Nacimiento" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Dirección" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fch_Creación" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Alias" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Imagen" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_insertar_persona" Method="sp_insertar_persona">
    <Parameter Name="per_nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="per_apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="per_cedula" Type="System.Int32" DbType="Int" />
    <Parameter Name="per_correo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="per_fch_nacimiento" Type="System.DateTime" DbType="Date" />
    <Parameter Name="per_direccion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="per_fch_creacion" Type="System.DateTime" DbType="Date" />
    <Parameter Name="per_imagen" Type="System.Data.Linq.Binary" DbType="Image" />
    <Parameter Name="per_estado" Type="System.String" DbType="Char(2)" />
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="VarChar(50)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>